### ISSUE TITLE
Cannot get past install

### ISSUE THREAD

**Issue by clairestreb** [ivmartel/dwv-vue#103]
Tried **yarn install**, but it failed. Tried **npm install**, and that failed, too. Please see attached file [2020-09-22T13_45_48_124Z-debug.log](https://github.com/ivmartel/dwv-vue/files/5261954/2020-09-22T13_45_48_124Z-debug.log) for error message. Any advice?

**Comment by ivmartel** [comment]
Did yarn give an error?

Regarding npm, it had troubles with ´geckodriver@1.20.0 postinstall script.´ (not part of this repo), did it give an error on the command line?

**Comment by clairestreb** [comment]
- yarn install: error An unexpected error occurred: "https://registry.yarnpkg.com/jszip/-/jszip-3.2.2.tgz: self signed certificate in certificate chain".
- npm install: geckodriver failure on command line:

`> geckodriver@1.20.0 postinstall C:\Users\VHACANStrebC\Downloads\dwv-vue\node_modules\geckodriver
> node index.js

Downloading geckodriver...
events.js:292
      throw er; // Unhandled 'error' event
      ^
ErrorClass [RequestError]: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\Users\VHACANStrebC\Downloads\dwv-vue\node_modules\got\index.js:69:21)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on DuplexWrapper instance at:
    at EventEmitter.emit (events.js:315:20)
    at ClientRequest.<anonymous> (C:\Users\VHACANStrebC\Downloads\dwv-vue\node_modules\got\index.js:69:7)
    at Object.onceWrapper (events.js:422:26)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-win64.zip'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geckodriver@1.20.0 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geckodriver@1.20.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VHACANStrebC\AppData\Roaming\npm-cache\_logs\2020-09-23T14_04_50_505Z-debug.log`

**Comment by ivmartel** [comment]
Both errors are related to dependency fetching that is independent of dwv. I hope these are temporary errors due to a bad package publish and that gets solved by the package maintainers. Both `npm install` and `yarn install` worked for me just now.
