### ISSUE TITLE
conflict with bootstrap css

### ISSUE THREAD

**Issue by javiCalvo** [ivmartel/dwv-vue#204]
Hi! Thanks for the project, I'm new with it and I'm having problems with the integration with bootstrap. The example it's made with angular material but my site uses bootstrap.

When I import the bootstrap css:

```js
import Vue from 'vue'
import App from './App.vue'
import index from "./router";
import BootstrapVue from 'bootstrap-vue'

import 'bootstrap/dist/css/bootstrap.css'  // <------ this import
import 'bootstrap-vue/dist/bootstrap-vue.css'


Vue.config.productionTip = false

Vue.use(BootstrapVue)

new Vue({
  router: index,
  render: h => h(App),
}).$mount('#app')
```

I'm unable to load any file, I'm getting this error:

```
Uncaught TypeError: r is not a function
    at Array.i (dwv.min.js?e730:3)
    at w.utils.ListenerHandler.fireEvent (dwv.min.js?e730:3)
    at HTMLDivElement.h (dwv.min.js?e730:3)
```

Any help would be appreciated as I really can't understand how the css can affect the js logic.

**Comment by ivmartel** [comment]
Ok, I'll investigate and come back to you.

**Comment by ivmartel** [comment]
When I update the current demo to get bootstrap (5.0.2) and bootstrap-vue (2.21.2) and change the `src/main.js`file to make it look like yours, everything works fine: I can start the app and load a dicom file. Which code base you you using?

If you still have the error, what you can do is replace the minified dist `dwv.min.js` with the non minified `dwv.js` in the `node_modules/dwv/dist/`, that way you will get more info on which function is not available.

**Comment by ivmartel** [comment]
@javiCalvo did you make some progress on this issue?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
