### ISSUE TITLE
Update to vue v3

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv-vue#313]
This project must update vue to v3, see
* announcement: https://blog.vuejs.org/posts/vue-3-one-piece.html
* migration guide: https://v3-migration.vuejs.org/

**Comment by ivmartel** [comment]
Notable change:
* [vue-cli](https://cli.vuejs.org/) is in maintenance mode, [vite](https://vitejs.dev/) is preferred
* which material lib? vue-material does not support v3 (see [issues/227](https://github.com/vuematerial/vue-material/issues/2277)), [vuetifyjs](https://vuetifyjs.com/en/) will support soon, [quasar](https://quasar.dev/) does...

**Comment by raducretu** [comment]
hello, is there any update of when will it be compatible with vue 3?

**Comment by ivmartel** [comment]
No time for that yet... All help appreciated!
