### ISSUE TITLE
Length not displaying on multi-framed images

### ISSUE THREAD

**Issue by markcNewell** [ivmartel/dwv-vue#51]
Firstly thank you for your work producing this.

I am running the component straight out of the box and it all works fine when parsing multiple URLs. However, when using a single image with multiple frames I try to draw on the image and get the following.

![image](https://user-images.githubusercontent.com/37421388/55899623-348b4600-5bbd-11e9-9d92-36ceab1516c2.png)

Any idea how to fix this or is this a known issue?

**Comment by ivmartel** [comment]
This is a tricky one since the data does not provide pixel size. One solution would be to use [US Region Calibration](http://dicom.nema.org/medical/dicom/2016e/output/chtml/part03/sect_C.8.5.5.html) if present. Follow ivmartel/dwv#641 for more and on the implementation progress.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
